name: optics_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  build: ^2.3.1
  freezed_annotation: ^2.4.2
  meta: ^1.8.0
  optics: ^0.0.1
  optics_annotations: any
  source_gen: ^1.2.6

dev_dependencies:
  lints: ^4.0.0
  test: ^1.16.0
  build_runner: ^2.1.4
